### PR TITLE
Force param to app aupdate and normalization of app id

### PR DESCRIPTION
**Pull request by mjakubowski84**
Hello Will!

While looking on the net I found your fork of the Marathon client. It looks like something I realy need. Please review this pull request. I added missing "force" param to the update method. I also upgraded the Feign library so it is possible to normalize app's id on the fly using new "Param" annotation.
There is a small test for it.

If you find this pull request ok then please merge it and please release a new version of the library. If you have any questions do not hesitate to ask.

Kind regards,
Marcin Jakubowski

### CODE REVIEW

**Comment by krystiannowak** [comment]
@willroden - travis seems to be passing :+1:  - hope to see it too soon as 0.4.6 in http://search.maven.org/#search|gav|1|g%3A%22cc.roden%22%20AND%20a%3A%22marathon-client%22

**Comment by krystiannowak** [comment]
Hello again @willroden - as your (and the source of the fork's) are the only forks that result in binaries in Central Repo http://search.maven.org/#search|ga|1|marathon - hope you can include this PR soon. Hope we (together with @mjakubowski84 ) won't need to create yet another groupId and artifactId and separate release of binary artifacts to Central just for that simple change to be available to the public. We are a bit _desperate_-ish about it, as we also would like to publish another tool to Central Repo which would have dependency on the functionality in this PR, so I guess you can see now the reason of our hassle.

**Comment by WillAbides** [comment]
I'm sorry I missed the original notification on this pull request. I will look at this when I get to the office in a couple of hours.

**Comment by krystiannowak** [comment]
@willroden Thanks! That will save us at least one additional configuration on sonatype.org ;)

**Comment by WillAbides** [comment]
This looks good, but I want to test this with a live marathon installation before I merge and release.  In the mean time, I released this as 0.4.6-SNAPSHOT.  You can grab it here:  https://oss.sonatype.org/content/repositories/snapshots/cc/roden/marathon-client/0.4.6-SNAPSHOT/

**Comment by WillAbides** [comment]
This is released as 0.4.6 on central now, but it isn't showing up in search on search

Thank you for submitting this, especially for including the feign upgrade.  I had been meaning to do that.

**Comment by krystiannowak** [comment]
Thanks @willroden Sure, let's wait till it propagates to search then!

**Pull request merged**
