### PR TITLE
Allow filtering in application set query.

### PR DESCRIPTION
**Pull request by seh**
Expose the command, ID, and label selector filter options [accepted by Marathon's "/v2/apps" GET method](https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/api/v2/AppsResource.scala#L48). All three are optional, in that Feign will drop any query parameters with a corresponding null argument value. Calling `Marathon#filterApps(null, null, null)` behaves indistinguishably from calling `Marathon#getApps()`.

The filtering implementation is defined by [`mesosphere.marathon.api.v2AppsResource.search()`](https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/api/v2/AppsResource.scala#L268). For the first two parameters (command and ID), Marathon will select only those applications that match the given command or ID when compared ignoring case.

The third label selector parameter obeys the format [documented in file _LabelSelector.scala_](https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/api/v2/LabelSelector.scala#L19).

Note that I did not overload `Marathon#getApps()`, but instead called this new method `filterApps()`. If you'd prefer to keep the name with an overload, I'm willing to change that.

### CODE REVIEW

**Comment by seh** [comment]
Note, by the way, that Marathon accepts a fourth parameter—_embed_—that [determines how much information it packs into each returned application record](https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/api/v2/AppsResource.scala#L54). I didn't think that was necessary to expose, given that it doesn't pertain to filtering the returned set. Let me know if you think we should include it anyway while we're here.

**Comment by seh** [comment]
Are there any objections to this patch?

**Comment by seh** [comment]
Six months later, is there any chance of getting this patch merged?

**Comment by mjakubowski84** [comment]
I will merge this on behalf of @WillAbides. I hope that he won't angry :)

**Comment by seh** [comment]
Thank you very much, @mjakubowski84. You just saved me from resurrecting my own fork. I was getting desperate.

However, if you _do_ think it would be healthy to focus on advancing a different fork (if @WillAbides has lost interest in this library), I'd be happy to help. I have several more improvements I'd like to make (including @gerlowskija's recent #18).

The forest of forks evident in the Github "network" graph is depressing. Each has something another is missing.

**Comment by mjakubowski84** [comment]
NP @seh. As I was granted rights by @WillAbides, I think that we can focus on this fork without spamming new ones. I hope that Will is ok about that and maybe will come to this project back.

**Comment by mjakubowski84** [comment]
And yep, @gerlowskija's issue is worth to bring it in here.

**Pull request merged**
